spring:
  application:
    name: springboot-demo-war
  data:
    rest:
      base-path: /hal
  thymeleaf:
    cache: false
    enabled: true
    encoding: utf-8
    mode: HTML
    suffix: .html
    prefix: classpath:/templates/
    